### ISSUE TITLE
Change  json to match the version 2.1.0

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_cityscopeJS#5]
1. 

Replace String (black,white,type, etc) by int and then precise in the 
````
"mapping":{"type":{"0":"RL","1":"RM","2":"RS","3":"OL","4":"OM","5":"OS","6":"ROAD"}
````

by 

````
"mapping":{"type":{"0":"BLACK","1":"WHITE","2":"type_0"}
````

2. This is still v2 compatible BUT it would be extremely nice to Remove (if possible) "objects":{"codes":

**Comment by RELNO** [comment]
`"objects":{"codes":` removed. As for [1], will close until Thursday, when we'll have a clear view of all changes.

**Comment by agrignard** [comment]
I reopen it as 1. is necessary to be compatible with v2 https://github.com/CityScope/CS_CityIO_Backend/wiki/Data-Format#mapping-dictionary 
we need something like this
```` 
"mapping":{"type":{"0":"BLACK","1":"WHITE","2":"type_0"}
````

**Comment by RELNO** [comment]
Fixed as of https://github.com/CityScope/CS_cityscopeJS/commit/de6f760eb8ec116cba2603e6f873be996ff743c6 onwards. Please check before reopening

**Comment by agrignard** [comment]
I don't see the change on this url 
https://cityio.media.mit.edu/api/table/CityScopeJS

**Comment by agrignard** [comment]
In this issue
1 is not yet solved I made a single issue #7 
and 
2 is indeed fixed (objects, codes)
